### PR TITLE
Added Spanish translation # 13

### PR DESCRIPTION
**Pull request by santteegt**
Added Spanish translation for plugin. PR includes both `.mo` and `.po` files in order to contribute to issue #13

### CODE REVIEW

**Comment by halink0803** [comment]
@santteegt Thank you for your PR. However, it seems you translated an outdated file from master, the updated file is on `develop` branch. I have uploaded your file to [transifex](https://www.transifex.com/halink0803/kyber-widget-woocommerce/translate/#es/woo-kyber-paymentpo/154472774) so you can easily check the untranslated words. Please check and updated your PR.

Thank you,

**Comment by santteegt** [comment]
Hi @halink0803. The transifex URL you provide is broken. Also, I can't access any file from this [URL](https://www.transifex.com/halink0803/kyber-widget-woocommerce/dashboard/) specified in the issue description. I checked the file on the `develop` branch as it looks the same

**Comment by halink0803** [comment]
@santteegt I can still check from my URL maybe it is required login. Anw, I have updated the file in `develop` branch. Sorry for not checking myself. I uploaded directly from my computer to transifex and forgot to commit :(. 

Please find the file [here](https://github.com/KyberNetwork/widget-woocommerce/blob/develop/languages/woo-kyber-payment.po)

**Comment by santteegt** [comment]
@halink0803 thanks for the update :) . I've just pushed the updated translation files to Spanish

**Comment by halink0803** [comment]
@santteegt uploaded and checked it cover 100% at [transifex](https://www.transifex.com/halink0803/kyber-widget-woocommerce/dashboard/). Thank you for your support. Merged PR.

**Pull request merged**
